appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: kYEUzV7LsBiVaQiaHc+TRtfBbsW9BaK+nsZdgcghpCwbFzdowf0oq0yMkX4QmRg00t//KIWx0FFjvt/W8dZDwEgg2DzdxW1XrFiJyMeW9DPe1GgpRrqXZ7S1xRMdoBy+E7xiq2JX5mRClslAV2quq+BeA51kNohddil/w+FxpzGW/UBpjLTpSLmrMltpr1g/D6cimL9vh9nIFt32K9h8H5qLiTeGmb/DwWsK7tJBtjpPvY7jlzmFjTV9/s5uqyAnrrimDX1W1PugqDmgSuwCS1uOn1lIfIc47/8DyOeS0m5Ti99I50pjd13CKzgR3Zpnbvbvbc2Ow9WJWNn1fXREZwAilIHUrsnngXROu0wmP1HSgJjL6+JhI6+3LH/NeByViajRdw4zsHGwRNZud6HJBvnaedwqz7/0rj2WpK1q2L3zgeKFrzrjJRUhC+RnzHaTE/NjpWg76UHuxaHR1uATGSRCFNiM+BvF44kbWZcMu8WQAqpDZRAuFuqwDqo4dwKbCQFUgVmL2x1U3bjNC7mj85ZG3z+ZtVavXTscT/36dzxuW5Jmh1p4ucP0E136ChY0xY9c4XjN7DOqMcEWpAH6anUhlJlrBQHIUHLdj6G+lmLUeLtimFSLWDgGy7YnaIBS+tuhgFLZsZjJibV7XQynHbGO2udijy1MS/Prpth+PAk=}
provider:
  win: azure
conda_forge_output_validation: true
